### ISSUE TITLE
Fix cydo issue

### ISSUE THREAD

**Issue by JohnCoates** [JohnCoatesOSS/Limitless#8]
Installing packages fails. Cydia uses cydo to execute commands as root (thanks @uroboro).
I recommend renaming it to runAsSuperuser and moving it from /usr/libexec/cydo into the Application folder if possible. We can't use Cydia's copy because it checks if it's being run by Cydia.
![img_0161](https://cloud.githubusercontent.com/assets/967800/20592257/4de6f898-b1e1-11e6-923d-914a8ffd5202.PNG)

**Comment by bolencki13** [comment]
This is the same issue I was describing with installing and removing packages with libAPTObjc. Technically if libAPTObjc runs in the library folder, rather than in the application folder or sandboxed, then this issue should be resolved. Otherwise we would need to build an additional helper to handle installation and removals. 

`[APTOManager  sharedCydiaManager]` rather than `[APTOManager sharedManager]`
This will also allow access to the sources input and used by Cydia.

**Comment by JohnCoates** [comment]
Sounds good. We'll still need this for running dpkg for now.

What are you thinking as far as how to integrate libAPTObjc. Should we just add the code to this repo or pull it in as a CocoaPod?

**Comment by bolencki13** [comment]
It might almost be easier to put on a repo since this way people can have access to it as well, they know what they are installing. It will make building a community around this easier I think, more trusting.

**Comment by uroboro** [comment]
[cydo.cpp#L95](https://github.com/JohnCoatesOSS/Limitless/blob/develop/Source/Legacy/cydo.cpp#L95) should be changed to reference Limitless' executable to execute dpkg as root. If the plan is to use libAPTObjc as single entry point, then it would become a bit more complicated to let the app that links to it use root.

**Comment by JohnCoates** [comment]
Cydo is now known as runAsSuperuser, and I've added the target to the Xcode project, and to the build script. Right now I'm getting error code 2 when trying to install something. Anyone can feel free to try and fix that, otherwise I'll give it a shot tomorrow

**Comment by JohnCoates** [comment]
I've fixed the runAsSuperuser issue, it was caused by not having runAsSuperuser owned by root and having the sticky bit set so it would always run as root
