### ISSUE TITLE
Limitless Crash when 3DTouching on Homescreen

### ISSUE THREAD

**Issue by leo98gomez** [JohnCoatesOSS/Limitless#89]
When I 3Dtouch on limitless on the Homescreen and chose the repo (BigBoss or Cydia/Telesphoreo) limitless launches as if it was about to open, but it then crashes. 
Here's the Crashlog: pastebin.com/XL4NSfL2
Syslog: pastebin.com/VZR3wS2A

**Comment by JohnCoates** [comment]
Thanks! Looks like it's crashing right here: https://github.com/JohnCoatesOSS/Limitless/blob/675d317a309aa0e869ae84b8cd30ded9f8e6b64a/Source/Application/Application.mm#L1376

I've attached your crashlog for posterity, since idk how long pastebin keeps things up.

[crashlog.txt](https://github.com/JohnCoatesOSS/Limitless/files/644098/XL4NSfL2.txt)

**Comment by JohnCoates** [comment]
I've fixed this in pull request #90
